### ISSUE TITLE
Error when package.json does not exist

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/drainpipe-dev#14]
When running `composer update` on an existing project:

```
$ composer update
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 2 updates, 0 removals
  - Upgrading lullabot/drainpipe-dev (dev-main 3823031 => dev-main fb62a89)
  - Upgrading mglaman/phpstan-drupal (0.12.11 => 0.12.12)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 2 updates, 0 removals
  - Downloading mglaman/phpstan-drupal (0.12.12)
  - Downloading lullabot/drainpipe-dev (dev-main fb62a89)
  - Upgrading mglaman/phpstan-drupal (0.12.11 => 0.12.12): Extracting archive
  - Upgrading lullabot/drainpipe-dev (dev-main 3823031 => dev-main fb62a89): Extracting archive
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Generating autoload files
ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class
74 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Using cached version of task v3.4.3 (a82117a3b560f35be9d5d34a1eb6707f1cdde1e2ab9ed22cd5a72bd97682a83e)

What about running composer thanks now?
This will spread some 💖  by sending a ★  to 60 GitHub repositories of your fellow package maintainers.
You can also run composer fund to discover how you can sponsor their work with some 💵

local-php-security-checker v1.0.0 (8c363d605116e84cf9ac28ac3838ca7979f7306916049bdb3f0f1fe2a8764d82) already exists in bin-dir, not overwriting.
Creating initial .ddev/docker-compose.selenium.yaml...
Creating initial nightwatch.conf.js...
Creating initial test/nightwatch/example.nightwatch.js...


  [Exception]
  package.json does not exist and was unable to be auto-created. Please create one.


update [--with WITH] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-autoloader] [--no-scripts] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...
```

**Comment by deviantintegral** [comment]
I can also replicate this with a fresh install on a new project.

**Comment by deviantintegral** [comment]
This is happening on my local because I have `nvm` installed, but I don't have it activated by default due to the performance hit it causes in loading a new terminal window.

At https://github.com/Lullabot/drainpipe-dev/blob/main/src/DevScaffoldInstallerPlugin.php#L222 we call yarn, but we never check that the process was successful. We should be calling `isSuccessful()` after `run()` to check the output code: https://symfony.com/doc/current/components/process.html#usage. That would properly have surfaced that `yarn` isn't in the path, instead of this other error.

As well, I don't know if we can 1) rely on every project using Nightwatch tests, and having a `package.json` and 2) using `yarn` versus `npm`. We _could_ decide to do that, but it needs discussion first. For reference, out of 3 other current anchor projects, 2 have no package.json (they use Drupal Test Traits and Behat, not Nightwatch), and one does have a package.json but is using npm and not yarn.

In the short term, could we log a warning instead of throwing a hard exception?

**Comment by justafish** [comment]
@deviantintegral this should be fixed now - it just checks for the existence of `package.json` and if it's there advises you what to install rather than installing it for you (this behaviour was changed in a different issue because it was causing yarn/npm to run inside the ddev container making it take forever for Macs)
