### ISSUE TITLE
Default to npm instead of yarn when setting up

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/drainpipe-dev#27]
Currently, if a project does not have a `package.json` the installer sets up the project using Yarn. However, Yarn 2 is not supported by dependabot, and npm has caught up significantly to yarn in the past few releases.

Let's still support yarn, but for new projects default to using npm.

**Comment by justafish** [comment]
It now explicitly asks you which package manager you'd like to use when running the Nightwatch setup
