### ISSUE TITLE
Check Nightwatch tests on an M1

### ISSUE THREAD

**Issue by justafish** [Lullabot/drainpipe-dev#36]
Follow up from https://github.com/drud/ddev/issues/3658#issuecomment-1059427858

**Comment by justafish** [comment]
tada! https://github.com/SeleniumHQ/docker-selenium/issues/1076#issuecomment-1053189663

**Comment by deviantintegral** [comment]
This looks to have been done at https://github.com/Lullabot/drainpipe-dev/pull/38
