### ISSUE TITLE
Support Drush v11

### ISSUE THREAD

**Issue by KalleVuorjoki** [Lullabot/drainpipe-dev#48]
Thanks for this project, looks great! I tried to include this to my project, but faced issue with Drush compatibility.

Drush v10 has reached end of life and v11 is only one recommended for Drupal 9.
If this project requires Drupal 8 support, maybe we could set `"drush/drush": "^10.5 || ^11.0",` in composer.json?

**Comment by KalleVuorjoki** [comment]
Oh, there's already a [pull request](https://github.com/Lullabot/drainpipe-dev/pull/47) trying to achieve this.

**Comment by justafish** [comment]
This is supported now in the latest release :tada:
