### ISSUE TITLE
Update selenium images.

### ISSUE THREAD

**Issue by YesCT** [Lullabot/drainpipe-dev#57]
While investigating confusing test fails we were seeing in the lullabot.com repo, @deviantintegral noticed when passwords were broken in our tests, that Selenium was crashing out due to an invalid command sent by the PHP side. And as part of debugging, tried updated Selenium and some other things, and noticed there were some available updates for the drainpipe selenium images.

This is the follow-up issue to update the selenium images.

**Comment by YesCT** [comment]
See https://github.com/Lullabot/lullabot.com-d8/pull/2153#issuecomment-1259586470 for background.

**Comment by justafish** [comment]
@YesCT thanks for opening this - just a friendly reminder that this repo is public whereas the background discussion you're linking to isn't, and so isn't visible to everyone reading this :smile_cat:

**Comment by YesCT** [comment]
@justafish ah! I'll update the summary with info.
